version: "3.8"

x-disabled: &disabled # Define a common option to disable automatic restart
  restart: "no"

services:
  postgres:
    image: postgres:latest
    container_name: dsi-postgres
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dsi_auth
    <<: *disabled
    volumes:
      - dsi_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: dsi-redis
    ports:
      - "63790:6379"
    <<: *disabled
    volumes:
      - dsi_redis_data:/data

volumes:
  dsi_postgres_data:
  dsi_redis_data:
